package hbi.core.des.dto;

/**Auto Generated By Hap Code Generator**/
import javax.persistence.*;

import com.hand.hap.mybatis.annotation.Condition;
import com.hand.hap.mybatis.annotation.ExtensionAttribute;
import com.hand.hap.mybatis.common.query.Comparison;
import com.hand.hap.mybatis.common.query.Where;
import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.Length;
import com.hand.hap.system.dto.BaseDTO;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;
@ExtensionAttribute(disable=true)
@Table(name = "STUDENT_INFO")
public class Info extends BaseDTO {

     public static final String FIELD_SID = "sid";
     public static final String FIELD_SNAME = "sname";
     public static final String FIELD_SAGE = "sage";
     public static final String FIELD_SSEX = "ssex";
     public static final String FIELD_SPHONE = "sphone";
     public static final String FIELD_SEMAIL = "semail";
     public static final String FIELD_ADMISSIONDATE = "admissiondate";
     public static final String FIELD_STATUS = "status";
     public static final String FIELD_GRADUATEDATE = "graduatedate";
    public static final String FIELD_SLNAME = "slname";




    @Id
     @GeneratedValue
     private Float sid;
//     @Where(
//            comparison = Comparison.LIKE
//     )
    @Condition(
            operator = "LIKE"
    )
     @Length(max = 25)
     private String sname;

     private Float sage;

     @Length(max = 2)
     private String ssex;

     private String sphone;

     @Email
     @Length(max = 254)
     private String semail;

     private Date admissiondate;

    @Length(
            max = 50
    )
    private String status;

    private Date graduatedate;

    @Length(max = 300)
    private String slname;


     public void setSid(Float sid){
         this.sid = sid;
     }

     public Float getSid(){
         return sid;
     }

     public void setSname(String sname){
         this.sname = sname;
     }

     public String getSname(){
         return sname;
     }

     public void setSage(Float sage){
         this.sage = sage;
     }

     public Float getSage(){
         return sage;
     }

     public void setSsex(String ssex){
         this.ssex = ssex;
     }

     public String getSsex(){
         return ssex;
     }

     public void setSphone(String sphone){
         this.sphone = sphone;
     }

     public String getSphone(){
         return sphone;
     }

     public void setSemail(String semail){
         this.semail = semail;
     }

     public String getSemail(){
         return semail;
     }

     public void setAdmissiondate(Date sbirthday){
         this.admissiondate = sbirthday;
     }

     public Date getAdmissiondate(){
         return admissiondate;
     }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getGraduatedate() {
        return graduatedate;
    }

    public void setGraduatedate(Date graduatedate) {
        this.graduatedate = graduatedate;
    }

    public String getSlname() {
        return slname;
    }

    public void setSlname(String slname) {
        this.slname = slname;
    }
}
